----------------------------------------
--Use the role to create and run tasks--
----------------------------------------
--begin

USE ROLE TASKADMIN4;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE SALES;
USE SCHEMA GOLD;

--===================================--
--Create tasks for DIM and FACT loading
--===================================--
--begin

USE ROLE ACCOUNTADMIN;
----DIM_STORE
CREATE OR REPLACE TASK SALES.GOLD.TASK_LOAD_DIM_STORE 
SCHEDULE = '1 minute' AS 

CALL SALES.GOLD.SP_LOAD_DIM_STORE();

----DIM_CUSTOMER
create or replace task SALES.GOLD.TASK_LOAD_DIM_CUSTOMER
	after SALES.GOLD.TASK_LOAD_DIM_STORE
	as CALL GOLD.SP_LOAD_DIM_CUSTOMER();
alter task SALES.GOLD.TASK_LOAD_DIM_CUSTOMER resume;

----DIM_PRODUCT
create or replace task SALES.GOLD.TASK_LOAD_DIM_PRODUCT
	after SALES.GOLD.TASK_LOAD_DIM_STORE
	as CALL GOLD.SP_LOAD_DIM_PRODUCT();
alter task SALES.GOLD.TASK_LOAD_DIM_PRODUCT resume;

----FACT_SALES
create or replace task SALES.GOLD.TASK_LOAD_FACT_SALES
	after SALES.GOLD.TASK_LOAD_DIM_CUSTOMER, SALES.GOLD.TASK_LOAD_DIM_PRODUCT
	as CALL GOLD.SP_LOAD_FACT_SALES();
alter task SALES.GOLD.TASK_LOAD_FACT_SALES resume;


ALTER TASK SALES.GOLD.TASK_LOAD_DIM_CUSTOMER RESUME;
ALTER TASK SALES.GOLD.TASK_LOAD_DIM_PRODUCT RESUME;
ALTER TASK SALES.GOLD.TASK_LOAD_FACT_SALES RESUME;

EXECUTE TASK SALES.GOLD.TASK_LOAD_DIM_STORE;


---------------------
--- Create SP for MetadataDB to update the next ETL date
CREATE OR REPLACE PROCEDURE METADATADB.PUBLIC.SP_PREPARE_NEXT_DATE()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    LET SQL_CMD := 
    '
    UPDATE METADATADB.PUBLIC.ETL_CONFIG_TABLE
    SET STATUS = 2
    WHERE STATUS = 1
    ';

    EXECUTE IMMEDIATE SQL_CMD;
    
    UPDATE METADATADB.PUBLIC.ETL_CONFIG_TABLE
    SET STATUS = 1
    WHERE ETL_CONFIG_KEY = (SELECT MIN(ETL_CONFIG_KEY) FROM METADATADB.PUBLIC.ETL_CONFIG_TABLE WHERE STATUS = 0);
    
    RETURN 'ETL Config updated';
END;

--- Create a task for this
CREATE OR REPLACE TASK METADATADB.PUBLIC.TK_PREPARE_NEXT_DATE
    schedule = '1 minute'
    as call METADATADB.PUBLIC.SP_PREPARE_NEXT_DATE();

