USE DATABASE SALES;
USE SCHEMA GOLD;
USE ROLE SYSADMIN;

-- Create DIM_STORE
CREATE OR REPLACE TABLE GOLD.DIM_STORE(
    STORE_KEY INT AUTOINCREMENT START 0 INCREMENT 1 PRIMARY KEY,
    STORE_ID INT,
    STORE_NAME VARCHAR,
    STORE_LOCATION VARCHAR,
    DWH_CREATE_DATE TIMESTAMP DEFAULT GETDATE()
);

-- CREATE DIM_CUSTOMER
CREATE OR REPLACE TABLE DIM_CUSTOMER(
    CUSTOMER_KEY INT AUTOINCREMENT START 0 INCREMENT 1 PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NUMBER VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    BIRTH_DATE DATE,
    MARITAL_STATUS VARCHAR,
    GENDER VARCHAR,
    CREATE_DATE DATE,
    LOYALTY_JOIN_DATE DATE,
    STORE_KEY INT,
    DWH_STATUS VARCHAR,
    DWH_START_DATE DATE,
    DWH_END_DATE DATE,
    DWH_CREATE_DATE TIMESTAMP DEFAULT GETDATE()
);

-- CREATE DIM_PRODUCT
CREATE OR REPLACE TABLE DIM_PRODUCT(
    PRODUCT_KEY INT AUTOINCREMENT START 0 INCREMENT 1 PRIMARY KEY,
	PRODUCT_ID INT,
	PRODUCT_NUMBER VARCHAR,
	PRODUCT_NAME VARCHAR,
    PRODUCT_CATEGORY VARCHAR,
	PRODUCT_SUBCATEGORY VARCHAR,
	PRICE DECIMAL(20,2), 
    DWH_STATUS VARCHAR,
    DWH_START_DATE DATE,
    DWH_END_DATE DATE,
    DWH_CREATE_DATE TIMESTAMP DEFAULT GETDATE()
);

-- CREATE DIM_DATE
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY    INT AUTOINCREMENT PRIMARY KEY,
    DATE        DATE,
    YEAR        INT,
    MONTH       INT,
    DAY         INT,
    MONTH_NAME  STRING,
    PERIOD      STRING
);


-- CREATE FACT_SALES
CREATE OR REPLACE TABLE FACT_SALES(
    ORDER_KEY INT AUTOINCREMENT PRIMARY KEY,
    ORDER_DATE_KEY INT,
    CUSTOMER_KEY INT,
    PRODUCT_KEY INT,
    STORE_KEY INT,
    SHIP_DATE_KEY INT,
	DUE_DATE_KEY INT,
    ORDER_NUMBER VARCHAR,
	SALES NUMBER(20,2),
	QUANTITY INT,
	PRICE NUMBER(20,2),
	POINTS_RECEIVED NUMBER(20,2),
	PAYMENT_CHANNEL VARCHAR,
	DWH_CREATE_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
