USE DATABASE SALES;
USE SCHEMA GOLD;
USE ROLE SYSADMIN;

-- Create DIM_STORE
CREATE OR REPLACE TABLE GOLD.DIM_STORE(
    STORE_KEY INT AUTOINCREMENT,
    STORE_ID INT,
    STORE_NAME VARCHAR,
    STORE_LOCATION VARCHAR,
    DWH_CREATE_DATE TIMESTAMP DEFAULT GETDATE()
);

-- CREATE DIM_CUSTOMER
CREATE OR REPLACE TABLE DIM_CUSTOMER(
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NUMBER VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    BIRTH_DATE DATE,
    MARITAL_STATUS VARCHAR,
    GENDER VARCHAR,
    CREATE_DATE DATE,
    LOYALTY_JOIN_DATE DATE,
    STORE_KEY INT,
    DWH_STATUS VARCHAR,
    DWH_START_DATE DATE,
    DWH_END_DATE DATE,
    DWH_CREATE_DATE TIMESTAMP DEFAULT GETDATE()
);
