USE DATABASE SALES;
USE SCHEMA GOLD;
USE ROLE SYSADMIN;

-- Load DIM_STORE
INSERT INTO
    GOLD.DIM_STORE 
SELECT
    IDENTITY,
    STOREID AS STOREID,
    STORENAME AS STORE_NAME,
    STORELOC AS STORE_LOCATION,
    GETDATE()
FROM
    SILVER.ERP_STORES;


-- Load DIM_CUSTOMER
-- Create a view for New Customers
CREATE OR REPLACE VIEW GOLD.VW_NEW_CUSTOMER_SRC AS
SELECT
        CI.CST_ID,
        CI.CST_KEY, -- CRM is the master so CRM_CUST_INFO.CST_KEY trumps ERP_CUST_AZ12.CID
        CI.CST_FIRSTNAME,
        CI.CST_LASTNAME,
        CA.BDATE,
        CI.CST_MARITAL_STATUS,
        CASE
            WHEN CI.CST_GNDR != 'N/A' THEN CI.CST_GNDR
            ELSE COALESCE(CA.GEN, 'N/A')
        END AS CST_GNDR_derived,
        CI.CST_CREATE_DATE,
        CI.CST_LOYALTY_JOIN_DATE,
        DS.STORE_KEY,
        'Current' AS DWH_STATUS,
        CAST(GETDATE() AS DATE) AS DWH_START_DATE,
        '9999-12-31' AS DWH_END_DATE,
        GETDATE() AS DWH_CREATE_DATE
    FROM
        SALES.SILVER.CRM_CUST_INFO CI
        LEFT JOIN SALES.SILVER.ERP_CUST_AZ12 CA
        ON CI.CST_KEY = RIGHT(CA.CID,LEN(CA.CID)-4)
        LEFT JOIN SALES.GOLD.DIM_STORE DS
        ON CI.CST_PREF_STORE = DS.STORE_KEY;

-- Merge to Update Expired rows and insert new records
    MERGE INTO GOLD.DIM_CUSTOMER AS TGT
    USING GOLD.VW_NEW_CUSTOMER_SRC AS SRC
        ON TGT.CUSTOMER_ID = SRC.CST_ID AND
        TGT.DWH_STATUS = SRC.DWH_STATUS
    
    WHEN MATCHED AND (
        TGT.CUSTOMER_NUMBER <> SRC.CST_KEY
        OR TGT.FIRST_NAME <> SRC.CST_FIRSTNAME
        OR TGT.LAST_NAME <> SRC.CST_LASTNAME
        OR TGT.BIRTH_DATE <> SRC.BDATE
        OR TGT.MARITAL_STATUS <> SRC.CST_MARITAL_STATUS
        OR TGT.GENDER <> SRC.CST_GNDR_derived
        OR TGT.CREATE_DATE <> SRC.CST_CREATE_DATE
        OR TGT.LOYALTY_JOIN_DATE <> SRC.CST_LOYALTY_JOIN_DATE
        OR TGT.STORE_KEY <> SRC.STORE_KEY
    )
    
    THEN 
    
    UPDATE SET
        TGT.DWH_STATUS = 'Expired',
        TGT.DWH_END_DATE = GETDATE() -- VARIABLE TO LOAD DATE
        
    WHEN NOT MATCHED
    THEN
        INSERT (CUSTOMER_ID, CUSTOMER_NUMBER, FIRST_NAME, LAST_NAME, BIRTH_DATE, MARITAL_STATUS, GENDER, CREATE_DATE, LOYALTY_JOIN_DATE, STORE_KEY, DWH_STATUS, DWH_START_DATE,    DWH_END_DATE, DWH_CREATE_DATE)
        VALUES (SRC.CST_ID, SRC.CST_KEY,SRC.CST_FIRSTNAME,SRC.CST_LASTNAME,SRC.BDATE,SRC.CST_MARITAL_STATUS,SRC.CST_GNDR_derived,SRC.CST_CREATE_DATE,SRC.CST_LOYALTY_JOIN_DATE, SRC.STORE_KEY, SRC.DWH_STATUS, SRC.DWH_START_DATE,SRC.DWH_END_DATE,SRC.DWH_CREATE_DATE
        )
;

--Then insert Current records
INSERT INTO GOLD.DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NUMBER, FIRST_NAME, LAST_NAME, BIRTH_DATE, MARITAL_STATUS, GENDER, CREATE_DATE, LOYALTY_JOIN_DATE, STORE_KEY, DWH_STATUS, DWH_START_DATE,    DWH_END_DATE, DWH_CREATE_DATE)
SELECT 
    SRC.*
FROM GOLD.VW_NEW_CUSTOMER_SRC AS SRC
LEFT JOIN GOLD.DIM_CUSTOMER AS TGT
        ON TGT.CUSTOMER_ID = SRC.CST_ID AND
        TGT.DWH_STATUS = SRC.DWH_STATUS
WHERE TGT.CUSTOMER_NUMBER IS NULL;


--Testing scripts
SELECT * FROM SILVER.CRM_CUST_INFO
WHERE CST_ID = '11000';

SELECT * FROM GOLD.DIM_CUSTOMER
WHERE CUSTOMER_ID = '11000'
;


    SELECT CUSTOMER_KEY, CUSTOMER_ID, MARITAL_STATUS, DWH_STATUS, DWH_START_DATE, DWH_END_DATE FROM GOLD.DIM_CUSTOMER
    WHERE CUSTOMER_ID = '11000';
    
    UPDATE GOLD.DIM_CUSTOMER 
    SET MARITAL_STATUS = 'Single', DWH_END_DATE = '9999-12-31', DWH_STATUS = 'Current'
    WHERE CUSTOMER_ID = '11000';

    UPDATE GOLD.DIM_CUSTOMER 
    SET MARITAL_STATUS = 'Single 3'
    WHERE CUSTOMER_KEY = '215001';

SELECT * FROM GOLD.VW_NEW_CUSTOMER_SRC
WHERE CST_ID = '11000';


