USE ROLE SYSADMIN;
USE DATABASE SALES;

-- Load SILVER.CRM_CUST_INFO
INSERT INTO
    SILVER.CRM_CUST_INFO
SELECT
    CST_ID,
    CST_KEY,
    TRIM(CST_FIRSTNAME) AS CST_FIRSTNAME,
    TRIM(CST_LASTNAME) AS CST_LASTNAME,
    CASE
        WHEN CST_MARITAL_STATUS = 'S' THEN 'Single'
        WHEN CST_MARITAL_STATUS = 'M' THEN 'Married'
        ELSE 'N/A'
    END AS CST_MARITAL_STATUS,
    CASE
        WHEN TRIM(UPPER(CST_GNDR)) IN ('F', 'FEMALE') THEN 'Female'
        WHEN TRIM(UPPER(CST_GNDR)) IN ('M', 'MALE') THEN 'Male'
        WHEN TRIM(UPPER(CST_GNDR)) = '' THEN 'N/A'
        ELSE IFNULL(CST_GNDR, 'N/A')
    END AS CST_GNDR,
    CST_CREATE_DATE,
    CST_LOYALTY_JOIN_DATE,
    CST_PREF_STORE,
    GETDATE()
FROM
    BRONZE.CRM_CUST_INFO;
-- Load SILVER.CRM_PRD_INFO
INSERT INTO
    SILVER.CRM_PRD_INFO
SELECT
    PRD_ID,
    PRD_KEY,
    PRD_NM,
    PRD_PRICE,
    GETDATE()
FROM
    BRONZE.CRM_PRD_INFO;
    
-- Load SILVER.CRM_SALES_DETAILS
INSERT INTO
    SILVER.CRM_SALES_DETAILS
SELECT
    SD.SLS_ORD_NUM,
    CASE
        WHEN LEN(SLS_PRD_KEY) != 8 THEN RIGHT(SLS_PRD_KEY, 8)
        ELSE SLS_PRD_KEY
    END AS SLS_PRD_KEY_correct,
    IFNULL(CI.CST_ID, '0') AS SLS_CUST_ID,
    SD.SLS_ORDER_DT,
    SD.SLS_SHIP_DT,
    SD.SLS_DUE_DT,
    CASE
        WHEN PRD.PRD_PRICE = SD.SLS_PRICE THEN SD.SLS_SALES
        WHEN PRD.PRD_PRICE != SD.SLS_PRICE THEN PRD.PRD_PRICE * SLS_QUANTITY
    END AS SLS_SALES_correct,
    SD.SLS_QUANTITY,
    SD.SLS_PRICE,
    ROUND(SLS_SALES_correct * 0.10,2) AS SLS_PTS_RCVD_correct,
    CASE
        WHEN SD.SLS_PYMNT_CHNNL = 0 THEN 'Card'
        WHEN SD.SLS_PYMNT_CHNNL = 1 THEN 'Cash'
        ELSE 'N/A'
    END AS SLS_PYMNT_CHNNL_correct,
    SD.SLS_STORE_ID
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY SLS_ORD_NUM
                ORDER BY
                    SLS_ORDER_DT DESC
            ) AS ROWNUM
        FROM
            BRONZE.CRM_SALES_DETAILS
    ) AS SD
    LEFT JOIN SILVER.CRM_PRD_INFO PRD ON SLS_PRD_KEY_correct = PRD.PRD_KEY
    LEFT JOIN SILVER.CRM_CUST_INFO CI ON SD.SLS_CUST_ID = CI.CST_ID
WHERE
    ROWNUM = 1
    ;

-- Load SILVER.ERP_CUST_AZ12
INSERT INTO 
    SILVER.ERP_CUST_AZ12
SELECT
    CID,
    BDATE,
    CASE
        WHEN TRIM(UPPER(GEN)) IN ('F', 'FEMALE') THEN 'Female'
        WHEN TRIM(UPPER(GEN)) IN ('M', 'MALE') THEN 'Male'
        WHEN TRIM(UPPER(GEN)) = '' THEN 'N/A'
        ELSE IFNULL(GEN, 'N/A')
    END AS GEN,
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY CID
                ORDER BY 
                    BDATE DESC
            ) AS ROWNUM
        FROM
            BRONZE.ERP_CUST_AZ12
    )
WHERE
    ROWNUM = 1;

-- Load SILVER.ERP_PX_CAT_G1V2
INSERT INTO 
  SILVER.ERP_PX_CAT_G1V2
SELECT
*
FROM 
    BRONZE.ERP_PX_CAT_G1V2;

-- Load SILVER.STORES
INSERT INTO 
  SILVER.ERP_STORES
SELECT
  *
FROM
    BRONZE.ERP_STORES;
