USE ROLE SYSADMIN;
USE DATABASE SALES;

SELECT 
    *
FROM BRONZE.CRM_CUST_INFO
LIMIT 100;

-- 1. Check if keys are unique
SELECT
    CST_ID,
    CST_KEY,
    COUNT(1)
FROM BRONZE.CRM_CUST_INFO
GROUP BY
    CST_ID,
    CST_KEY
HAVING 
    COUNT(1)>1 OR
    CST_ID IS NULL OR 
    CST_KEY IS NULL
;

-- 2. Check if there are no spaces
SELECT 
    CST_FIRSTNAME,
    CST_LASTNAME
FROM
    BRONZE.CRM_CUST_INFO
WHERE
    CST_FIRSTNAME != TRIM(CST_FIRSTNAME) OR
    CST_LASTNAME != TRIM(CST_LASTNAME);

-- 3. Check values for Marital Status
SELECT
    DISTINCT CST_MARITAL_STATUS
FROM 
    BRONZE.CRM_CUST_INFO;

-- 4. Check values for Gender
SELECT
    DISTINCT CST_GNDR
FROM
    BRONZE.CRM_CUST_INFO;

-- 5. Check Create and Loyalty Join Dates
SELECT 
    CST_CREATE_DATE,
    CST_LOYALTY_JOIN_DATE
FROM BRONZE.CRM_CUST_INFO
--WHERE CST_LOYALTY_JOIN_DATE < CST_CREATE_DATE;
WHERE CST_LOYALTY_JOIN_DATE IS NULL;

-- 6. Check Preferred Store FK
SELECT 
    DISTINCT CST_PREF_STORE
FROM
    BRONZE.CRM_CUST_INFO;
