USE ROLE sysadmin;
USE DATABASE sales;

SELECT 
    *
FROM
    BRONZE.CRM_SALES_DETAILS
WHERE 
    SLS_ORD_NUM IN ('SO300007','SO300019','SO300020')
ORDER BY
    SLS_ORD_NUM
LIMIT 100;


-- 1. Check if keys are unique
SELECT
    SLS_ORD_NUM,
    COUNT(1)
FROM
    BRONZE.CRM_SALES_DETAILS
GROUP BY
    SLS_ORD_NUM
HAVING 
    COUNT(1)>1 OR
    SLS_ORD_NUM IS NULL
;

-- 2. Check if Product Keys match
SELECT 
    A.SLS_PRD_KEY,
    B.PRD_KEY,
FROM
    BRONZE.CRM_SALES_DETAILS A
    LEFT JOIN BRONZE.CRM_PRD_INFO B
    ON A.SLS_PRD_KEY = B.PRD_KEY
WHERE
    B.PRD_ID IS NOT NULL;

-- 3. Check if Customer Keys match
SELECT 
    A.SLS_CUST_ID,
    B.CST_ID,
FROM
    BRONZE.CRM_SALES_DETAILS A
    LEFT JOIN BRONZE.CRM_CUST_INFO B
    ON A.SLS_CUST_ID = B.CST_ID
WHERE
    B.CST_ID IS NULL
ORDER BY
    A.SLS_CUST_ID;
--107092, 102210, 119993

-- 4. Check if dates follow the process
SELECT
    *
FROM 
    BRONZE.CRM_SALES_DETAILS
WHERE
    (SLS_ORDER_DT > SLS_SHIP_DT OR SLS_ORDER_DT > SLS_DUE_DT);


-- 5. Check if Price in POS matches with Product Master Data
SELECT
    CASE
        WHEN LEN(SLS_PRD_KEY) != 8 THEN RIGHT(SLS_PRD_KEY, 8)
        ELSE SLS_PRD_KEY
    END AS SLS_PRD_KEY_correct,
    SLS_PRICE,
    SLS_QUANTITY,
    SLS_SALES,
    PRD_PRICE 
FROM
    BRONZE.CRM_SALES_DETAILS AS SD
    LEFT JOIN SILVER.CRM_PRD_INFO AS PRD
    ON SLS_PRD_KEY_correct = PRD.PRD_KEY
WHERE
    SD.SLS_PRICE != PRD.PRD_PRICE;
