USE ROLE ACCOUNTADMIN;
USE DATABASE SALES;


-- 1. Dynamic Truncate
CREATE OR REPLACE PROCEDURE SILVER.SP_TRUNCATE_TABLES(TBL_NAME STRING)
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
     EXECUTE IMMEDIATE
$$
    TRUNCATE TABLE $$ || TBL_NAME || $$
$$;
    
    RETURN 'Table ' || TBL_NAME || ' truncated successfully.';
END;

-- 2. SP Manager that Loop 
CREATE OR REPLACE PROCEDURE SALES.SILVER.SP_TRUNCATE_MANAGER()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE
    SQL_CMD STRING;
    RS RESULTSET;
BEGIN
    RS := (SELECT 
            CONCAT(DATABASENAME,''.'',SCHEMANAME,''.'',TABLENAME) AS TABLENAME_VAR
        FROM
            METADATADB.PUBLIC.ETL_LOAD_ORDER
        ORDER BY 
            RUNORDER);
            
    FOR rec in RS DO
        SQL_CMD := ''CALL SALES.SILVER.SP_TRUNCATE_TABLES('''''' || rec.TABLENAME_VAR || '''''')'';
        EXECUTE IMMEDIATE SQL_CMD;
    END FOR;

    RETURN ''Truncated Dynamically'';
END';

call SALES.SILVER.SP_TRUNCATE_TABLES();

--- 3. CREATE TRUNCATE TASK
create or replace task SALES.SILVER.TK_TRUNCATE_TABLES
	warehouse=COMPUTE_WH
	schedule='1 minute'
	as CALL SALES.SILVER.SP_TRUNCATE_MANAGER();


EXECUTE TASK SALES.SILVER.TK_TRUNCATE_TABLES;

SELECT COUNT(1) FROM SILVER.POS_SALES_DETAILS; -- 50000
SELECT COUNT(1) FROM SILVER.CRM_CUST_INFO; -- 10509
SELECT COUNT(1) FROM SILVER.CRM_PRD_INFO; -- 306 
SELECT COUNT(1) FROM SILVER.ERP_CUST_AZ12; -- 10509
SELECT COUNT(1) FROM SILVER.ERP_PX_CAT_G1V2; -- 306
SELECT COUNT(1) FROM SILVER.ERP_STORES;


