USE ROLE ACCOUNTADMIN;
USE DATABASE SALES;

-- Silver Truncate
-- TRUNCATE SP (reusable)
CREATE OR REPLACE PROCEDURE SILVER.SP_TRUNCATE_TABLES(TBL_NAME STRING)
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
     EXECUTE IMMEDIATE
$$
    TRUNCATE TABLE $$ || TBL_NAME || $$
$$;
    
    RETURN 'Table ' || TBL_NAME || ' truncated successfully.';
END;
