USE ROLE ACCOUNTADMIN;
USE DATABASE SALES;

-- Loop Truncate 
CREATE OR REPLACE PROCEDURE SALES.SILVER.TEST_TRUNCATE_LIST()
RETURNS STRING
LANGUAGE SQL
AS
DECLARE
    SQL_CMD STRING;
    RS RESULTSET;
BEGIN
    RS := (SELECT 
            CONCAT(DATABASENAME,'.',SCHEMANAME,'.',TABLENAME) AS TABLENAME_VAR
        FROM
            METADATADB.PUBLIC.ETL_LOAD_ORDER
        ORDER BY 
            RUNORDER);
            
    FOR rec in RS DO
        SQL_CMD := 'CALL SALES.SILVER.SP_TRUNCATE_TABLES(''' || rec.TABLENAME_VAR || ''')';
        EXECUTE IMMEDIATE SQL_CMD;
    END FOR;

    RETURN 'Truncated Dynamically';
END ;

call SALES.SILVER.TEST_TRUNCATE_LIST();

--- CREATE TRUNCATE TASK acts as Root task
CREATE OR REPLACE TASK SALES.SILVER.TEST_TRUNCATE_TASK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 minute'
    AS

    CALL SALES.SILVER.TEST_TRUNCATE_LIST();
;
EXECUTE TASK SALES.SILVER.TEST_TRUNCATE_TASK;

SELECT COUNT(1) FROM SILVER.POS_SALES_DETAILS; -- 50000
SELECT COUNT(1) FROM SILVER.CRM_CUST_INFO; -- 10509
SELECT COUNT(1) FROM SILVER.CRM_PRD_INFO; -- 306 
SELECT COUNT(1) FROM SILVER.ERP_CUST_AZ12; -- 10509
SELECT COUNT(1) FROM SILVER.ERP_PX_CAT_G1V2; -- 306
SELECT COUNT(1) FROM SILVER.ERP_STORES;

