
USE ROLE ACCOUNTADMIN;
USE DATABASE METADATADB;

CREATE OR REPLACE TABLE ETL_LOAD_ORDER(
    RUNORDER INT AUTOINCREMENT START 1 INCREMENT 1,
    DATABASENAME STRING,
    SCHEMANAME STRING,
    TABLENAME STRING,
    LOADPROCEDURE STRING
);

INSERT INTO ETL_LOAD_ORDER (
    
    DATABASENAME,
    SCHEMANAME,
    TABLENAME,
    LOADPROCEDURE
)

--VALUES ('SALES','SILVER','CRM_CUST_INFO','SP_LOAD_CRM_CUST_INFO');
--VALUES ('SALES','SILVER','CRM_PRD_INFO','SP_LOAD_CRM_PRD_INFO');
-- VALUES ('SALES','SILVER','ERP_CUST_AZ12','SP_LOAD_ERP_CUST_AZ12');
-- VALUES ('SALES','SILVER','ERP_PX_CAT_G1V2','SP_LOAD_ERP_PX_CAT_G1V2');
-- VALUES ('SALES','SILVER','ERP_STORES','SP_LOAD_ERP_STORES');
VALUES ('SALES','SILVER','POS_SALES_DETAILS','SP_LOAD_POS_SALES_DETAILS');

SELECT * FROM ETL_LOAD_ORDER;
