USE ROLE ACCOUNTADMIN;
CREATE DATABASE METADATADB;

--
CREATE OR REPLACE TABLE ETL_CONFIG_TABLE (
    ETL_CONFIG_KEY INT AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    DATE DATE,
    DAY INT,
    MONTH INT,
    YEAR INT,
    STATUS INT
);

--LOAD DATA IN ETL CONFIG TABLE
INSERT INTO ETL_CONFIG_TABLE
WITH date_range AS (
    SELECT
        DATEADD(DAY, SEQ4(), '2023-01-01') AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 1461)) -- ~100 years of days
    WHERE DATE_VALUE <= '2100-12-31'
)
SELECT
    ROW_NUMBER() OVER(ORDER BY DATE_VALUE),
    CAST(DATE_VALUE AS DATE) DATE_VALUE,
    DAY(DATE_VALUE) AS DAY,
    MONTH(DATE_VALUE) AS MONTH_NUMBER,
    YEAR(DATE_VALUE) AS YEAR,
    '0' AS STATUS
FROM DATE_RANGE
WHERE
    DAY(DATE_VALUE) = 1
    AND YEAR(DATE_VALUE) IN (2023,2024,2025)
;
