-------------------------
--Create TASKADMIN role--
-------------------------
--begin

--Use ACCOUNTADMIN role to create the role
USE ROLE ACCOUNTADMIN;

CREATE ROLE TASKADMIN4;

--Grant the role to the current user
GRANT ROLE TASKADMIN4 TO USER JMMSANPEDRO1;

--Grant privileges to the role:
GRANT CREATE TASK ON SCHEMA GOLD TO ROLE TASKADMIN4;
GRANT EXECUTE TASK, EXECUTE MANAGED TASK ON ACCOUNT TO ROLE TASKADMIN4;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TASKADMIN4;
GRANT USAGE ON DATABASE SALES TO ROLE TASKADMIN4;
GRANT USAGE ON SCHEMA GOLD TO ROLE TASKADMIN4;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOLD TO ROLE TASKADMIN4;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GOLD TO ROLE TASKADMIN4;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA GOLD TO ROLE TASKADMIN4;

--GRANT ON BRONZE
GRANT CREATE TASK ON SCHEMA BRONZE TO ROLE TASKADMIN4;
GRANT USAGE ON SCHEMA BRONZE TO ROLE TASKADMIN4;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BRONZE TO ROLE TASKADMIN4;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA BRONZE TO ROLE TASKADMIN4;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA BRONZE TO ROLE TASKADMIN4;

--GRANT ON SILVER
GRANT CREATE TASK ON SCHEMA SILVER TO ROLE TASKADMIN4;
GRANT USAGE ON SCHEMA SILVER TO ROLE TASKADMIN4;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA SILVER TO ROLE TASKADMIN4;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SILVER TO ROLE TASKADMIN4;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SILVER TO ROLE TASKADMIN4;

--Check grants
SHOW GRANTS TO ROLE TASKADMIN4;

--end
