----------------------------------------
--Use the role to create and run tasks--
----------------------------------------
--begin

USE ROLE TASKADMIN4;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE SALES;
USE SCHEMA GOLD;

--Test if the role can access the tables
SELECT * FROM SALES.GOLD.DIM_STORE; 

--Create task
CREATE OR REPLACE TASK SALES.GOLD.TASK_TEST
--WAREHOUSE = COMPUTE_WH --> use Snowflake Serverless compute
SCHEDULE = '1 minute' AS
INSERT INTO 
    SALES.GOLD.DIM_STORE 
        (
            STORE_NAME
        )
VALUES
    (
    'MAR'
    );

--Test if the role can execute task
EXECUTE TASK SALES.GOLD.TASK_TEST;


--end

--===================================--
--Create tasks for DIM and FACT loading
--===================================--
--begin

----DIM_STORE
CREATE OR REPLACE TASK SALES.GOLD.TASK_LOAD_DIM_STORE 
SCHEDULE = '1 minute' AS 

CALL SALES.GOLD.SP_LOAD_DIM_STORE();

----DIM_CUSTOMER
CREATE OR REPLACE TASK SALES.GOLD.TASK_LOAD_DIM_CUSTOMER
AFTER SALES.GOLD.TASK_LOAD_DIM_STORE
AS 

CALL GOLD.SP_LOAD_DIM_CUSTOMER();

----DIM_PRODUCT
CREATE OR REPLACE TASK GOLD.TASK_LOAD_DIM_PRODUCT 
AFTER SALES.GOLD.TASK_LOAD_DIM_CUSTOMER
AS 

CALL GOLD.SP_LOAD_DIM_PRODUCT();

----FACT_SALES
CREATE OR REPLACE TASK SALES.GOLD.TASK_LOAD_FACT_SALES
AFTER GOLD.TASK_LOAD_DIM_PRODUCT 
AS
CALL GOLD.SP_LOAD_FACT_SALES();


ALTER TASK SALES.GOLD.TASK_LOAD_DIM_CUSTOMER RESUME;
ALTER TASK SALES.GOLD.TASK_LOAD_DIM_PRODUCT RESUME;
ALTER TASK SALES.GOLD.TASK_LOAD_FACT_SALES RESUME;

EXECUTE TASK SALES.GOLD.TASK_LOAD_DIM_STORE;

