USE ROLE ACCOUNTADMIN;
USE DATABASE SALES;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA SILVER TO ROLE TASKADMIN4;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SILVER TO TASKADMIN4;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SILVER TO TASKADMIN4;
GRANT CREATE PROCEDURE ON SCHEMA SILVER TO ROLE TASKADMIN4;

--TEST 1: TRUNCATE TASK -> TASK 1 AND TASK 2 RUN ON PARALLEL
EXECUTE TASK SALES.SILVER.TEST_TRUNCATE_TASK;

-- 1 OF 2
CREATE OR REPLACE TASK SALES.SILVER.TK_LOAD_CRM_PRD
    WAREHOUSE = COMPUTE_WH
    --SCHEDULE = '1 minute'
    AFTER SALES.SILVER.TEST_TRUNCATE_TASK
    AS
        --CALL SALES.SILVER.SP_TRUNCATE_LOAD_CRM_PRD();
    CALL SALES.SILVER.SP_LOAD_CRM_PRD_INFO();
;
ALTER TASK SALES.SILVER.TK_LOAD_CRM_PRD SUSPEND;


-- 2 OF 2
CREATE OR REPLACE TASK SALES.SILVER.TK_LOAD_CRM_CUST
    WAREHOUSE = COMPUTE_WH
    --SCHEDULE = '1 minute'
    AFTER SALES.SILVER.TEST_TRUNCATE_TASK
    AS

    CALL SALES.SILVER.SP_LOAD_CRM_CUST_INFO();
;
ALTER TASK SALES.SILVER.TK_LOAD_CRM_CUST SUSPEND;




