USE ROLE ACCOUNTADMIN;
USE DATABASE SALES;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA SILVER TO ROLE TASKADMIN4;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SILVER TO TASKADMIN4;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SILVER TO TASKADMIN4;
GRANT CREATE PROCEDURE ON SCHEMA SILVER TO ROLE TASKADMIN4;

USE ROLE TASKADMIN4;
-- 1 OF 3 ERP
CREATE OR REPLACE TASK SALES.SILVER.TK_LOAD_ERP_STORES
    WAREHOUSE = COMPUTE_WH
    --SCHEDULE = '1 minute'
    AFTER SALES.SILVER.TEST_TRUNCATE_TASK
    AS

    CALL SALES.SILVER.SP_LOAD_ERP_STORES();
;
ALTER TASK SALES.SILVER.TK_LOAD_ERP_STORES SUSPEND;

-- 2 OF 3 ERP
CREATE OR REPLACE TASK SALES.SILVER.TK_LOAD_ERP_PX
    WAREHOUSE = COMPUTE_WH
    --SCHEDULE = '1 minute'
    AFTER SALES.SILVER.TEST_TRUNCATE_TASK
    AS

    CALL SALES.SILVER.SP_LOAD_ERP_PX_CAT_G1V2();
;
ALTER TASK SALES.SILVER.TK_LOAD_ERP_PX SUSPEND;

-- 3 OF 3 ERP
CREATE OR REPLACE TASK SALES.SILVER.TK_LOAD_ERP_CUST
    WAREHOUSE = COMPUTE_WH
    --SCHEDULE = '1 minute'
    AFTER SALES.SILVER.TEST_TRUNCATE_TASK
    AS

    CALL SALES.SILVER.SP_LOAD_ERP_CUST_AZ12();
;
ALTER TASK SALES.SILVER.TK_LOAD_ERP_CUST SUSPEND;
