USE ROLE ACCOUNTADMIN;
USE DATABASE SALES;

-- 1 OF 1
CREATE OR REPLACE TASK SALES.SILVER.TK_LOAD_POS_SALES_DETAILS
    WAREHOUSE = COMPUTE_WH
    --SCHEDULE = '1 minute'
    AFTER SALES.SILVER.TEST_TRUNCATE_TASK
    AS

    CALL SALES.SILVER.SP_LOAD_POS_SALES_DETAILS();
;
ALTER TASK SALES.SILVER.TK_LOAD_POS_SALES_DETAILS SUSPEND;
