USE ROLE ACCOUNTADMIN;
USE DATABASE SALES;

-- Load SILVER.STORES 1 of 2 SILVER CRM tables
-- Load SILVER.CRM_PRD_INFO
CREATE OR REPLACE PROCEDURE SILVER.SP_LOAD_CRM_PRD_INFO_PARAM(V_YEAR INT, V_MONTH INT)
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    LET SQL_CMD STRING :=
    
    '
    INSERT INTO
        SILVER.CRM_PRD_INFO
    SELECT
        PRD_ID,
        PRD_KEY,
        PRD_NM,
        PRD_PRICE,
        GETDATE()
    FROM
        SALES.BRONZE.CRM_PRD_INFO_EXT
    WHERE
        SRC_YEAR = ' || V_YEAR || ' AND
        SRC_MONTH = ' || V_MONTH ;

    EXECUTE IMMEDIATE SQL_CMD;
    
    RETURN 'Successful Loading of SALES.SIlVER.CRM_PRD_INFO_EXT';
END
;


--------
-- Load SILVER.CRM_CUST_INFO 2 of 2 SILVER CRM TABLES
CREATE OR REPLACE PROCEDURE SILVER.SP_LOAD_CRM_CUST_INFO_PARAM(V_YEAR INT, V_MONTH INT)
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    LET SQL_CMD STRING :=
    '
    INSERT INTO 
        SALES.SILVER.CRM_CUST_INFO
    SELECT
        CST_ID,
        CST_KEY,
        TRIM(CST_FIRSTNAME) AS CST_FIRSTNAME,
        TRIM(CST_LASTNAME) AS CST_LASTNAME,
        CASE
            WHEN CST_MARITAL_STATUS = ''S'' THEN ''Single''
            WHEN CST_MARITAL_STATUS = ''M'' THEN ''Married''
            ELSE ''N/A''
        END AS CST_MARITAL_STATUS,
        CASE
            WHEN TRIM(UPPER(CST_GNDR)) IN (''F'', ''FEMALE'') THEN ''Female''
            WHEN TRIM(UPPER(CST_GNDR)) IN (''M'', ''MALE'') THEN ''Male''
            WHEN TRIM(UPPER(CST_GNDR)) = '''' THEN ''N/A''
            ELSE IFNULL(CST_GNDR, ''N/A'')
        END AS CST_GNDR,
        CST_CREATE_DATE,
        CST_LOYALTY_JOIN_DATE,
        CST_PREF_STORE,
        GETDATE()
    FROM
        SALES.BRONZE.CRM_CUST_INFO_EXT
    WHERE
        SRC_YEAR = ' || V_YEAR || ' AND
        SRC_MONTH = ' || V_MONTH;

    EXECUTE IMMEDIATE SQL_CMD;
        
    RETURN 'Successful Loading of SALES.SIlVER.CRM_CUST_INFO';
END
; 
