USE ROLE ACCOUNTADMIN;
USE DATABASE SALES;

--- SILVER Loop: Stored Procedure Manager 
CREATE OR REPLACE PROCEDURE SALES.SILVER.SP_LOAD_MANAGER()
    RETURNS STRING
    LANGUAGE SQL
    AS
    DECLARE 
        SQL_CMD STRING;
        RS RESULTSET;
    BEGIN
        LET P_YEAR INT := (select year FROM METADATADB.PUBLIC.ETL_CONFIG_TABLE WHERE STATUS = 1);
        LET P_MONTH INT:= (select month FROM METADATADB.PUBLIC.ETL_CONFIG_TABLE WHERE STATUS = 1);

        RS := (SELECT 
                    CONCAT(DATABASENAME,'.',SCHEMANAME,'.',LOADPROCEDURE) AS LOADPROCEDURE_VAR
                FROM
                    METADATADB.PUBLIC.ETL_LOAD_ORDER
                ORDER BY 
                    RUNORDER);

        FOR rec in RS DO
            SQL_CMD := 'CALL ' || rec.LOADPROCEDURE_VAR || '(' || P_YEAR || ', ' || P_MONTH || ')';
            EXECUTE IMMEDIATE SQL_CMD;
        END FOR;

    RETURN SQL_CMD;
    --RETURN 'Truncated Dynamically';
END;

-- Task for SILVER Loop
CREATE OR REPLACE TASK SALES.SILVER.TK_LOAD_LOOP
    AFTER SALES.SILVER.TEST_TRUNCATE_TASK
    AS
    CALL SALES.SILVER.SP_LOAD_MANAGER();
;
ALTER TASK SALES.SILVER.TK_LOAD_LOOP RESUME;
